# Generated by Django 5.2.16 on 2026-07-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0004_academy_created_by_academy_updated_by_and_more'),
        ('organizations', '0002_organizationmembership_membership_user_active_idx_and_more'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organization', 'status'], name='program_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['academy', 'status'], name='program_academy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organization', 'is_featured'], name='program_org_featured_idx'),
        ),
    ]
