# Generated by Django 5.2.16 on 2026-07-18 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationBusiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('business_type', models.CharField(choices=[('online_academy', 'Online academy'), ('corporate_training', 'Corporate training'), ('church_ministry', 'Church or ministry school'), ('trade_school', 'Trade school'), ('coaching', 'Coaching business'), ('certification', 'Certification program'), ('membership', 'Membership community'), ('custom', 'Custom')], max_length=40)),
                ('mission', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('transformation_promise', models.TextField(blank=True)),
                ('delivery_model', models.JSONField(blank=True, default=dict)),
                ('revenue_model', models.JSONField(blank=True, default=dict)),
                ('blueprint', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_businesses', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='unique_business_slug_per_org')],
            },
        ),
    ]
