# Generated by Django 5.2.16 on 2026-07-19 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('organizations', '0002_organizationmembership_membership_user_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='educationbusiness',
            index=models.Index(fields=['organization', 'is_active'], name='business_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='educationbusiness',
            index=models.Index(fields=['organization', 'business_type'], name='business_org_type_idx'),
        ),
    ]
