# Generated by Django 5.2.16 on 2026-07-19 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='membership_org_role_idx'),
        ),
    ]
