# Generated by Django 5.2.16 on 2026-07-22 01:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(help_text='Random server-generated filename. Never use the client filename.', max_length=255, unique=True)),
                ('storage_key', models.CharField(help_text='Relative key beneath the private upload root. Do not store an absolute operating-system path.', max_length=500, unique=True)),
                ('file_extension', models.CharField(max_length=20)),
                ('declared_mime_type', models.CharField(blank=True, max_length=127)),
                ('detected_mime_type', models.CharField(blank=True, max_length=127)),
                ('file_size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sha256', models.CharField(blank=True, db_index=True, help_text='Lowercase hexadecimal SHA-256 digest.', max_length=64)),
                ('status', models.CharField(choices=[('quarantined', 'Quarantined'), ('validating', 'Validating'), ('rejected', 'Rejected'), ('scanning', 'Scanning'), ('ready_for_extraction', 'Ready for extraction'), ('extracting', 'Extracting'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='quarantined', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('validation_started_at', models.DateTimeField(blank=True, null=True)),
                ('validation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('malware_scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('malware_scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_started_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_file_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('temporary_text_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='knowledge.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('knowledge_profile', models.JSONField(blank=True, default=dict)),
                ('opportunity_map', models.JSONField(blank=True, default=dict)),
                ('builder_recommendations', models.JSONField(blank=True, default=list)),
                ('engine_version', models.CharField(blank=True, help_text='Version of the Knowledge Engine that generated this record.', max_length=64)),
                ('failure_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='knowledge_k_status_9f41ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'is_active'], name='knowledge_w_owner_i_c55796_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'created_at'], name='knowledge_w_owner_i_8b8b43_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_workspace_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['workspace', 'status'], name='knowledge_k_workspa_738e60_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['workspace', 'created_at'], name='knowledge_k_workspa_3c6f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['status', 'created_at'], name='knowledge_k_status_6c7e8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gte', 0)), name='knowledge_source_file_size_nonnegative'),
        ),
    ]
