# Generated by Django 5.2.16 on 2026-07-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated completion time in minutes.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated completion time in minutes.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated completion time in minutes.', null=True),
        ),
    ]
