# Generated by Django 5.2.16 on 2026-07-18 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_estimated_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated completion time in minutes.', null=True)),
                ('activity_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('brain_lab', 'Brain Lab'), ('quiz', 'Quiz'), ('coding_exercise', 'Coding Exercise'), ('cybersecurity_lab', 'Cybersecurity Lab'), ('ai_tutor_session', 'AI Tutor Session'), ('assignment', 'Assignment'), ('download', 'Download'), ('live_event', 'Live Event')], max_length=40)),
                ('order', models.PositiveIntegerField(default=1, help_text="The activity's position inside the lesson.")),
                ('is_required', models.BooleanField(default=True, help_text='Whether learners must complete this activity.')),
                ('points_possible', models.PositiveIntegerField(default=0, help_text='Maximum points available for this activity.')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Type-specific activity settings, such as video URLs, quiz rules, lab configuration, or event details.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.lesson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['lesson', 'order'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'slug'), name='unique_activity_slug_per_lesson'), models.UniqueConstraint(fields=('lesson', 'order'), name='unique_activity_order_per_lesson')],
            },
        ),
    ]
