# Generated by Django 5.2.16 on 2026-07-19 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0004_academy_created_by_academy_updated_by_and_more'),
        ('courses', '0006_alter_activity_status_alter_course_status_and_more'),
        ('organizations', '0002_organizationmembership_membership_user_active_idx_and_more'),
        ('programs', '0002_program_created_by_program_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'status'], name='course_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['academy', 'status'], name='course_acad_status_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['program', 'status'], name='course_prog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'is_featured'], name='course_org_featured_idx'),
        ),
    ]
