# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_course_org_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="The activity's position inside the lesson.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="The lesson's position inside the module.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="The module's position inside the course.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
