# Generated by Django 5.2.16 on 2026-07-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={'ordering': ['name'], 'verbose_name': 'Academy', 'verbose_name_plural': 'Academies'},
        ),
    ]
