# Generated by Django 5.2.16 on 2026-07-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_alter_academy_options'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies', to='businesses.educationbusiness'),
        ),
    ]
