# Generated by Django 5.2.16 on 2026-07-19 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_academy_business'),
        ('businesses', '0002_educationbusiness_business_org_active_idx_and_more'),
        ('organizations', '0002_organizationmembership_membership_user_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['organization', 'is_active'], name='academy_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['organization', 'is_public'], name='academy_org_public_idx'),
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['business', 'is_active'], name='academy_business_active_idx'),
        ),
    ]
